[project]
name = "chiyono-samsnugnotesynchronizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9.13"
dependencies = [
    "pyqt6>=6.9.1",
]
